### ISSUE TITLE
Usage/install commands in README

### ISSUE THREAD

**Issue by rjc** [qbit/dotfiles#2]
Hi,

Usage/installation instructions are rendered as a single line:

`
git clone https://github.com/qbit/dotfiles.git
cd dotfiles
./install -v
`

Instead of:

    git clone https://github.com/qbit/dotfiles.git
    cd dotfiles
    ./install -v

This is due to \` (backtick) being used for the whole block instead of prepending each line with `    ` (four spaces).

Regards,

rjc

**Comment by qbit** [comment]
Thanks :D
