### ISSUE TITLE
"ksh: battery: not found" error in OpenBSD-current

### ISSUE THREAD

**Issue by NanXiao** [qbit/dotfiles#3]
Hi,

Greeting from me!

I use this awesome framework in `OpenBSD-current`, but it generates following error:  

```
root@OpenBSD(%)[0]:~$ echo $SHELL
/bin/ksh
ksh: battery: not found
```

Could you help to check it? Thanks very much in advance!

Best Regards
Nan Xiao

**Comment by qbit** [comment]
So `battery` is a [toy utility](https://code.bolddaemon.com/qbit/utils/) I made to show battery status. You could easily simulate it via a script similar to this:

```
#!/bin/sh

/usr/sbin/apm -l
```

Make it `+x` and put it in `~/bin/battery`.
